[2021-09-22 00:39:08,603] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: dbt_dag.dbt_run 2020-09-22T00:00:00+00:00 [queued]>
[2021-09-22 00:39:08,614] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: dbt_dag.dbt_run 2020-09-22T00:00:00+00:00 [queued]>
[2021-09-22 00:39:08,614] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-09-22 00:39:08,615] {taskinstance.py:1096} INFO - Starting attempt 1 of 2
[2021-09-22 00:39:08,615] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-09-22 00:39:08,626] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): dbt_run> on 2020-09-22T00:00:00+00:00
[2021-09-22 00:39:08,632] {standard_task_runner.py:52} INFO - Started process 39615 to run task
[2021-09-22 00:39:08,653] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_run', '2020-09-22T00:00:00+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', '/Users/daniel/sensor-data-ELT/dags/dbt_run.py', '--cfg-path', '/var/folders/pz/3j4hm0tj07g0nnp6bk493r040000gn/T/tmph68u345z', '--error-file', '/var/folders/pz/3j4hm0tj07g0nnp6bk493r040000gn/T/tmp1ezaygis']
[2021-09-22 00:39:08,655] {standard_task_runner.py:77} INFO - Job 6: Subtask dbt_run
[2021-09-22 00:39:13,740] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_dag.dbt_run 2020-09-22T00:00:00+00:00 [running]> on host Daniels-MacBook-Pro.local
[2021-09-22 00:39:18,790] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=noreply@astronomer.io
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2020-09-22T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-09-22T00:00:00+00:00
[2021-09-22 00:39:18,791] {subprocess.py:52} INFO - Tmp dir root location: 
 /var/folders/pz/3j4hm0tj07g0nnp6bk493r040000gn/T
[2021-09-22 00:39:18,792] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'dbt run']
[2021-09-22 00:39:18,801] {subprocess.py:74} INFO - Output:
[2021-09-22 00:39:20,401] {subprocess.py:78} INFO - Running with dbt=0.19.0
[2021-09-22 00:39:20,402] {subprocess.py:78} INFO - Encountered an error:
[2021-09-22 00:39:20,402] {subprocess.py:78} INFO - Runtime Error
[2021-09-22 00:39:20,403] {subprocess.py:78} INFO -   fatal: Not a dbt project (or any of the parent directories). Missing dbt_project.yml file
[2021-09-22 00:39:20,541] {subprocess.py:82} INFO - Command exited with return code 2
[2021-09-22 00:39:20,549] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/daniel/sensor-data-ELT/dbt-env/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/daniel/sensor-data-ELT/dbt-env/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/daniel/sensor-data-ELT/dbt-env/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/daniel/sensor-data-ELT/dbt-env/lib/python3.7/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-09-22 00:39:20,553] {taskinstance.py:1513} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_run, execution_date=20200922T000000, start_date=20210921T213908, end_date=20210921T213920
[2021-09-22 00:39:20,604] {local_task_job.py:151} INFO - Task exited with return code 1
[2021-09-22 00:39:20,631] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-09-22 01:19:22,911] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: dbt_dag.dbt_run 2020-09-22T00:00:00+00:00 [queued]>
[2021-09-22 01:19:22,919] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: dbt_dag.dbt_run 2020-09-22T00:00:00+00:00 [queued]>
[2021-09-22 01:19:22,920] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-09-22 01:19:22,920] {taskinstance.py:1096} INFO - Starting attempt 1 of 2
[2021-09-22 01:19:22,920] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-09-22 01:19:22,927] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): dbt_run> on 2020-09-22T00:00:00+00:00
[2021-09-22 01:19:22,930] {standard_task_runner.py:52} INFO - Started process 41096 to run task
[2021-09-22 01:19:22,938] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_dag', 'dbt_run', '2020-09-22T00:00:00+00:00', '--job-id', '2', '--pool', 'default_pool', '--raw', '--subdir', '/Users/daniel/sensor-data-ELT/dags/dbt_run.py', '--cfg-path', '/var/folders/pz/3j4hm0tj07g0nnp6bk493r040000gn/T/tmpdqj_ighu', '--error-file', '/var/folders/pz/3j4hm0tj07g0nnp6bk493r040000gn/T/tmphsrvw0c1']
[2021-09-22 01:19:22,940] {standard_task_runner.py:77} INFO - Job 2: Subtask dbt_run
[2021-09-22 01:19:27,985] {logging_mixin.py:109} INFO - Running <TaskInstance: dbt_dag.dbt_run 2020-09-22T00:00:00+00:00 [running]> on host Daniels-MacBook-Pro.local
[2021-09-22 01:19:33,026] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=noreply@astronomer.io
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2020-09-22T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-09-22T00:00:00+00:00
[2021-09-22 01:19:33,027] {subprocess.py:52} INFO - Tmp dir root location: 
 /var/folders/pz/3j4hm0tj07g0nnp6bk493r040000gn/T
[2021-09-22 01:19:33,028] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'cd sensor-data-dbt; dbt run']
[2021-09-22 01:19:33,036] {subprocess.py:74} INFO - Output:
[2021-09-22 01:19:33,040] {subprocess.py:78} INFO - bash: line 0: cd: sensor-data-dbt: No such file or directory
[2021-09-22 01:19:34,345] {subprocess.py:78} INFO - Running with dbt=0.19.0
[2021-09-22 01:19:34,345] {subprocess.py:78} INFO - Encountered an error:
[2021-09-22 01:19:34,346] {subprocess.py:78} INFO - Runtime Error
[2021-09-22 01:19:34,346] {subprocess.py:78} INFO -   fatal: Not a dbt project (or any of the parent directories). Missing dbt_project.yml file
[2021-09-22 01:19:34,485] {subprocess.py:82} INFO - Command exited with return code 2
[2021-09-22 01:19:34,492] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/daniel/sensor-data-ELT/dbt-env/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/daniel/sensor-data-ELT/dbt-env/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/daniel/sensor-data-ELT/dbt-env/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/daniel/sensor-data-ELT/dbt-env/lib/python3.7/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-09-22 01:19:34,495] {taskinstance.py:1513} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=dbt_run, execution_date=20200922T000000, start_date=20210921T221922, end_date=20210921T221934
[2021-09-22 01:19:34,515] {local_task_job.py:151} INFO - Task exited with return code 1
[2021-09-22 01:19:34,534] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
